### ISSUE TITLE
Champion Collector

### ISSUE THREAD

**Issue by Long-HaHoang** [Long-HaHoang/League_Collector#1]
## Value Proposition

**As a** USER
**I want to** see all champions on a list
**so that**  I can choose what champion I already have

## Description

... (Wireframe, scribble, design, or text)

## Acceptance Criteria

- [ ] Champions are displayed in a gallery
- [ ] Pressing a champion will highlight the item
- [ ] A counter is displayed

## Tasks

- [ ] Create a champion page 
- [ ] Download both JSON from the league dev site
- [ ] Eventually mod the JSON files.

## Complexity

(Size L)
