### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by Long-HaHoang** [Long-HaHoang/League_Collector#2]
# Userstory

## Value Proposition

**As an** Author/Developer
**I want to** have a landing, imprint, and data privacy page
**so that** I can be legally on the safe site

## Description

Simple landing page with legal stuff link in the footer.

## Acceptance Criteria

- [x] Imprint and data privacy page link is displayed in the footer
- [x] The link routes the user to the respective page
- [x] The back button is displayed

## Tasks

- [x] Create a landing page with a layout
- [x] Add two links to the footer
- [x] Create pages for imprint and data privacy

## Complexity

(Size M)
